spring:
  application:
    name: cai-api-backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
  #    timeout: 5000
  #    password:
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/caiapi
    username: root
    password: root
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
  #  elasticsearch:
  #    uris: http://localhost:9200
  #    username: root
  #    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

# 对象存储
aliyun:
  oss:
    endpoint: oss-cn-heyuan.aliyuncs.com
    accessKeyId: LTAI5tNKp6qXeTvq2yehaGv8
    accessKeySecret: teUyZvvNh9gXtbQZiq2c8mEgBi7voM
    bucketName: cai-api-project



cai:
  gateway:
    host: http://localhost:8090

dubbo:
  application:
    name: cai-api-admin-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://172.17.0.2:8848